version: 2

sources:
  - name: staging
    database: streaming-pipeline-418713 # BigQuery project id
    schema: company_house # BigQuery data set
    tables:
      - name: company_house_core
      - name: company_house_stream
  - name: production
    database: streaming-pipeline-418713 # BigQuery project id
    schema: prod # BigQuery data set
    tables:
      - name: company_house_core
      - name: get_last_timestamp
      - name: snapshot_streamed_data
  